model_params:
  name: 'CategoricalVAE'
  in_channels: 3
  latent_dim: 512
  categorical_dim: 40
  temperature: 0.5
  anneal_rate: 0.00003
  anneal_interval: 100
  alpha: 1.0

exp_params:
  dataset: clevr
  data_path: "./data/"
  img_size: 64
  batch_size: 144
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  n_workers: 0
  max_train_images: 10_000
  max_val_images: 3_000

trainer_params:
  gpus: [0]
  max_epochs: 100

logging_params:
  save_dir: "./logs/"
  name: "cvae"
  manual_seed: 1995
